### ISSUE TITLE
Allow to show a history of actions

### ISSUE THREAD

**Issue by pbek** [pbek/nextcloud-gpodder#1]
### Todo

- [x] Show list of 10 actions
    - [x] Sort by `timestamp_epoch` desc
    - [x] Only show `action == PLAY` (selectable)
- [x] Allow to download mp3 of episode
- [x] Show podcast name
    - data needs to be downloaded an parsed
    - see `\OCA\GPodderSync\Core\PodcastData\PodcastDataReader::fetchPodcastData` and `\OCA\GPodderSync\Core\PodcastData\PodcastData`
- [x] Show episode name
    - data needs to be downloaded an parsed
\Core\PodcastData\PodcastData`
- [x] Allow to open web link of episode
    - data needs to be downloaded an parsed
- [x] Show total time
- [x] Show podcast episode image
    - data needs to be downloaded an parsed
    - [ ] `content Security Policy: The page’s settings blocked the loading of a resource at https://tuxdigital.com/wp-content/uploads/twil214-square-thumbnail.jpg (“img-src”)`
- [x] "Load more" button
- [x] Fix tests
- [x] Media Player with progress  support (set time where to start playback)?
    - Also has CSP issues

### Optional

- [-] Pagination for more than 10 items?
    - "Load more" button is enough

Upstream issue: https://github.com/thrillfall/nextcloud-gpodder/issues/111

**Comment by pbek** [comment]
<img width="907" alt="image" src="https://user-images.githubusercontent.com/1798101/221195243-7dba0e80-9ef8-4203-a4a2-178288054a75.png">

**Comment by pbek** [comment]
The CSP issue can't be fixed for admin pages. Will be addressed in https://github.com/pbek/nextcloud-nextpod.
